@startuml
title カウントの表示

package Domain {

    package Entity {

        interface ICountEntity {
            int Value
        }

        class CountEntity {
            int Value
        }
    }

    package Structure {
        interface IPresentationCountStructure {
            string CountText
        }
        class PresentationCountStructure {
            string CountText
        }
    }

    package Translator {
        class CountTranslator {
            IPresentationScore Translate(ICountEntity entity)
        }
    }

    package UseCase {

        interface IRenderCountUseCase {
            void Render(ICountEntity entity)
        }

        interface ICountTranslator {
            IPresentationScore Translate(ICountEntity entity)
        }

        interface ICountPresenter {
            void Render(IPresentationCountStructure structure)
        }

        class RenderCountInteractor {
            void Render(ICountEntity entity)
        }

    }

}

package Presentation {

    package Presenter {
        interface ICountView {
            void Render(IPresentationCountStructure structure)
        }
        class CountPresenter {
            void Render(IPresentationCountStructure structure)
        }
    }

    package View {
        class CountView {
            void Render(IPresentationCountStructure structure)
        }
    }
}

ICountEntity <|.. CountEntity

IPresentationCountStructure <|.. PresentationCountStructure

IRenderCountUseCase <|.. RenderCountInteractor
IRenderCountUseCase ..> ICountEntity

ICountTranslator <|.. CountTranslator
CountTranslator ..> ICountEntity
CountTranslator ..> IPresentationCountStructure

RenderCountInteractor ..> ICountEntity
RenderCountInteractor ..> ICountTranslator
RenderCountInteractor ..> ICountPresenter

ICountPresenter <|.. CountPresenter
ICountPresenter ..> IPresentationCountStructure
CountPresenter ..> ICountView
CountPresenter ..> IPresentationCountStructure

ICountView <|.. CountView
ICountView ..> IPresentationCountStructure
CountView ..> IPresentationCountStructure

@enduml